version: "3.4"

services:
  netgearparser:
    image: netgearparser
    network_mode: bridge
    container_name: NetgearParser
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        MODEM_PASSWORD: password
        INFLUX_URL: "http://influxdb:8086"
        INFLUX_DB: modem
        FREQUENCY_MINUTES: 1
        
